# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# shows the active branch of the repo in your current directory
[git_branch]
# disable git branch in favor of work tree path
disabled = false

[directory]
# Whether or not to truncate to the root of the git repo that you're currently in.
truncate_to_repo = false


