abbr --add --global v 'nvim'
abbr --add --global vi 'nvim'
abbr --add --global vim 'nvim'
abbr --add --global cat 'bat'
abbr --add --global ls 'exa --long --all --icons'
abbr --add --global la 'exa --long --all --icons'
abbr --add --global lt 'exa --tree --all --level 2 --icons'
abbr --add --global tree 'exa --tree --all --level 2 --icons'
abbr --add --global sf 'source ~/.config/fish/config.fish'
abbr --add --global edf 'nvim ~/personal/dotfiles'
abbr --add --global oc 'nvim ~/.config'
abbr --add --global gclb 'git clone --bare'
abbr --add --global gc 'git commit -v -m'
abbr --add --global gpu 'git push -u origin HEAD'
abbr --add --global gwl 'git worktree list'
abbr --add --global gwa 'git worktree add'
abbr --add --global gwr 'git worktree remove'
# git branch "prune", remove all branches that have been prunned (removed remotelly) but still exist locally"
abbr --add --global gbp "git branch -vv | awk '/: gone]/{print \$1}' | xargs git branch -D"

