abbr --add --global v 'nvim'
abbr --add --global vi 'nvim'
abbr --add --global vim 'nvim'
abbr --add --global cat 'bat'
abbr --add --global ls 'exa --long --all --icons'
abbr --add --global la 'exa --long --all --icons'
abbr --add --global lt 'exa --tree --all --level 2 --icons'
abbr --add --global tree 'exa --tree --all --level 2 --icons'
abbr --add --global sf 'source ~/.config/fish/config.fish'
abbr --add --global edf 'nvim ~/personal/dotfiles'
abbr --add --global oc 'nvim ~/.config'
abbr --add --global gclb 'git clone --bare'
abbr --add --global gc 'git commit -v -m'

