abbr --add --global v 'nvim'
abbr --add --global n 'npm'
abbr --add --global p 'pnpm'
abbr --add --global cat 'bat'
abbr --add --global ls 'eza --long --all --icons'
abbr --add --global la 'eza --long --all --icons'
abbr --add --global lt 'eza --tree --all --level 2 --icons'
abbr --add --global tree 'eza --tree --all --level 2 --icons'
abbr --add --global sf 'source ~/.config/fish/config.fish'
abbr --add --global edf 'nvim ~/personal/dotfiles'
abbr --add --global oc 'nvim ~/.config'
abbr --add --global gclb 'git_clone_bare'
abbr --add --global gc 'git commit -v -m'
abbr --add --global gpu 'git push -u origin HEAD'
abbr --add --global gwl 'git worktree list'
abbr --add --global gwa 'git worktree add'
abbr --add --global gwr 'git worktree remove'
abbr --add --global gjm "git jump merge"
abbr --add --global gbc "git_branch_cleanup"
