# yaml-language-server: $schema=https://dlvhdr.github.io/gh-dash/configuration/gh-dash/schema.json
prSections:
  - title: To Review
    filters: is:open -author:@me updated:>={{ nowModify "-12w" }} sort:updated-desc
  - title: Involved
    filters: is:open involves:@me -author:@me updated:>={{ nowModify "-12w" }} sort:updated-desc
  - title: My Pull Requests
    filters: is:open author:@me updated:>={{ nowModify "-12w" }} sort:updated-desc
    layout:
      author:
        hidden: true
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 150
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal: []
  issues: []
  prs:
    - key: c
      name: Code review
      command: >
        set repo_name (string split '/' -- "{{.RepoName}}")[2] &&
        set session_name "$repo_name/{{.PrNumber}}" &&
        set pr_path "{{.RepoPath}}/{{.PrNumber}}" &&
        tmux new-session -d -s "$session_name" -c {{.RepoPath}} -n "review" '
        git_branch_cleanup &&
        cd main &&
        git pull &&
        cd .. &&
        git worktree add {{.PrNumber}} -b {{.HeadRefName}} origin/{{.HeadRefName}} &&
        cd {{.PrNumber}} &&
        npm install &&
        nvim -c ":silent Octo pr edit {{.PrNumber}}" &&
        fish
        ' &&
        tmux switch-client -t "$session_name"
    - key: d
      name: Diff
      command: >
        set repo_name (string split '/' -- "{{.RepoName}}")[2] &&
        set session_name "$repo_name/{{.PrNumber}}" &&
        set pr_path "{{.RepoPath}}/{{.PrNumber}}" &&
        tmux new-session -d -s "$session_name" -c {{.RepoPath}} -n "review" '
        git_branch_cleanup &&
        cd main &&
        git pull &&
        cd .. &&
        git worktree add {{.PrNumber}} -b {{.HeadRefName}} origin/{{.HeadRefName}} &&
        cd {{.PrNumber}} &&
        npm install &&
        nvim -c ":DiffviewOpen main...{{.HeadRefName}} --imply-local" &&
        fish
        ' &&
        tmux switch-client -t "$session_name"

  branches: []
repoPaths:
  oneaudi/*: ~/repos/oneaudi/*
  arielschiavoni/*: ~/repos/arielschiavoni/*
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
pager:
  diff: ""
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
