# yaml-language-server: $schema=https://dlvhdr.github.io/gh-dash/configuration/gh-dash/schema.json
prSections:
- title: My Pull Requests
  filters: is:open author:@me updated:>={{ nowModify "-3w" }} sort:updated-desc
  layout:
    author:
      hidden: true
- title: Needs My Review
  filters: is:open review-requested:@me updated:>={{ nowModify "-3w" }} sort:updated-desc
- title: Involved
  filters: is:open involves:@me -author:@me updated:>={{ nowModify "-3w" }} sort:updated-desc
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 150
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal: []
  issues: []
  prs:
    - key: c
      name: Code review
      command: >
        tmux switch-client -t review &&
        tmux kill-window -a -t review &&
        tmux new-window -c {{.RepoPath}} -t review '
        gh pr checkout {{.PrNumber}} &&
        cd ../main &&
        git pull &&
        cd ../review &&
        nvim -c ":silent Octo pr edit {{.PrNumber}}"
        ' &&
        tmux new-window -c {{.RepoPath}} -t review '
        npm install &&
        npm run build &&
        fish
        ' &&
        tmux kill-window -t review:1
    - key: d
      name: Diff
      command: >
        tmux switch-client -t review &&
        tmux kill-window -a -t review &&
        tmux new-window -c {{.RepoPath}} -t review '
        gh pr checkout {{.PrNumber}} &&
        cd ../main &&
        git pull &&
        cd ../review &&
        nvim -c ":DiffviewOpen main...{{.HeadRefName}} --imply-local"
        ' &&
        tmux new-window -c {{.RepoPath}} -t review '
        npm install &&
        npm run build &&
        fish
        ' &&
        tmux kill-window -t review:1

  branches: []
repoPaths:
  oneaudi/*: ~/code/work/*
  oneaudi/falcon-renderer: ~/code/work/falcon-renderer/review
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
pager:
  diff: ""
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: false
